Repository NOAA-FIMS/FIMS, pull requests merged in 2022-03, with the labels that each got.

#22 Fix #15 clang tidy workflow bug
  .github/workflows/clang-tidy.yml
  .github/workflows/run-clang-tidy.yml
  CMakeLists.txt
  Makefile
  tests/gtest/CMakeLists.txt
  tests/gtest/benchmark_place_holder1.cpp
  tests/gtest/test_place_holder1.cpp
  tests/gtest/test_place_holder2.cpp
Labels: bug

#21 Fix #7 upload googletest log if workflow failed
  .github/workflows/run-googletest.yml
Labels: enhancement

#50 fix: include stdint.h in common/model_object to recognize uint32_t type
  .Rbuildignore
  inst/include/common/model_object.hpp
Labels: emergency fix

#49 Bug fix compiling issue
  CMakeLists.txt
  inst/include/common/model_object.hpp
  inst/include/def.hpp
  inst/include/fims_math.hpp
Labels: emergency fix

#54 Fix bug for feat-issue-17-logistic-selectivity-module
  .Rbuildignore
  CMakeLists.txt
  NAMESPACE
  inst/include/def.hpp
  inst/include/interface/interface.hpp
  src/FIMS.cpp
Labels: kind: bug
