Repository NOAA-FIMS/FIMS, pull requests merged in 2024-06, with the labels that each got.

#615 fix rec_nll evaluate bug
  inst/include/interface/rcpp/rcpp_objects/rcpp_recruitment.hpp
  vignettes/fims-demo.Rmd
Labels: kind: bug

#620 fix: use correct way of getting tmb output
  vignettes/fims-demo.Rmd
Labels: kind: bug, vignette

#631 Fixes label on bug issue template and adds reprex guidance
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: kind: bug, kind: documentation

#628 fix(data_mile1): sd of log(x) instead of CV
  R/data_mile1.R
  data-raw/data_mile1.R
  data/data_mile1.rda
  man/data_mile1.Rd
Labels: kind: bug, P3, theme: code cleanup
