Repository NOAA-FIMS/FIMS, pull requests merged in 2024-12, with the labels that each got.

#694 stops printing pointer addresses to the screen
  inst/include/interface/rcpp/rcpp_objects/rcpp_interface_base.hpp
  vignettes/fims-demo.Rmd
Labels: kind: refactor, P3, theme: code cleanup

#698 add mainpage for doxygen with link to other documentation
  inst/include/common/mainpage.dox
Labels: kind: documentation, attribute: low hanging 🍎

#696 reorganize information to improve readability
  inst/include/common/information.hpp
  inst/include/common/model.hpp
  inst/include/interface/rcpp/rcpp_interface.hpp
  tests/testthat/testthat-problems.rds
Labels: kind: refactor, P3, theme: code cleanup

#708 fix(initialize_modules) to return a named list
  R/fimsfit.R
  R/initialize_modules.R
  man/create_FIMSFit.Rd
  man/fit_fims.Rd
  tests/testthat/helper-integration-tests-setup.R
  tests/testthat/test-initialize_modules.R
  tests/testthat/test-integration-fims-estimation-with-wrappers.R
  vignettes/fims-demo.Rmd
  vignettes/logging_system.Rmd
Labels: kind: feature, theme: code cleanup

#703 Fixes up the contributor acknowledgements in repo
  .github/workflows/call-allcontributors.yml
  DESCRIPTION
  README.md
Labels: kind: documentation, P3, theme: documentation
